launcher:
  results: out/results  # [optional] save results to this directory
  repeat: 2             # [optional] repeat each experiment for this number of times
  save: true            # [optional] save results to disk
  loglevel: INFO        # [optional] log level [CRITICAL, ERROR, WARNING, INFO, DEBUG], default INFO
  snapshot: true        # [optional] If create snapshot of the experiment
  verbose: false        # [optional] Save detailed information for each repeat run
  packages: []          # [optional] Record the version of these packages
  algorithms: [ADDFBO, BO, BO_LIGHT]  # run these algorithms
  problems: [tetci2019, arxiv2017]  # run each algorithm on these problems

reporter:  # [optional] config for reporter
  results: out/results             # load results from this directory, default: launcher.results
  formats: [curve, excel, violin]  # generate these formats of reports, default: [curve]
  algorithms:                      # config for each algorithm, default: [launcher.algorithms]
    - [BO, BO_LIGHT]      # make comparison on these algorithms
    - [ADDFBO, BO]        # and these algorithms
  problems: [tetci2019, arxiv2017]  # use results that algorithms runs on these problems, default: [launcher.problems]
  params:  # config for report formats, use 'pyfmto list' and 'pyfmto show' to see available options and its params
    curve:
      on_log_scale: true  # plot on log scale
      merge: True         # merge all plots into one figure
      suffix: '.jpg'      # save plots with this suffix (.svg and .pdf can't be merged)
    violin:
      quality: 5

algorithms:   # [optional] config for each algorithm
  BO_LIGHT:   # config for BO ablation study and use this name
    base: BO  # str: specify the base algorithm
    client:
      ts_trials: 500  # default is 1000

problems:  # [optional] config for each problem
  tetci2019:
    dim: 3         # int|[int]: dimension of the tasks
    fe_init: 11    # int: initial FE, which is sampled by random when a task is initialized, default is dim * 5
    fe_max: 25     # int: maximum FE, make sure this value is larger than fe_init, default is dim * 11
    npd: 1         # int|[int]: number of partitions per dimension, default is 1
    seed: 123      # int|[int]: random seed, default is 123
    random_ctrl: weak  # str: random control, other options are 'strong', 'no', default is 'weak'
  arxiv2017:
    dim: 3
    fe_init: 20
    fe_max: 25

  # Notes:
  # 1. If a configuration was labeled [optional] in the comment, it is not required to specify it in the config file.
  # 2. The 'int|[int]' in the problem parameters' comments means it support multiple values. e.g. 'dim: [3, 5]'.
  # 3. All problem support other parameters (configured in tetci2019) except 'dim'.
  # 4. See README for more instructions.