launcher:
  results: out/results
  repeat: 10
  save: true
  algorithms: [BO, BO_LIGHT]
  problems: [tetci2019, arxiv2017]

reporter:
  results: /Users/zxx/Workspace/Results
  algorithms:
    - [BO, BO_LIGHT]
  problems: [tetci2019, arxiv2017]

algorithms:
  BO_LIGHT:  # config for an ablation version
    base: BO  # specify the base algorithm
    client:
      ts_trials: 500  # default is 1000